"""Incremental graph update logic.

Detects changed files via git diff, re-parses only changed + impacted files,
and updates the graph accordingly. Also supports CLI invocation for hooks.
"""

from __future__ import annotations

import ast
import fnmatch
import hashlib
import logging
import subprocess
import time
from pathlib import Path
from typing import Optional

from .graph import GraphStore
from .parser import CodeParser, EdgeInfo

logger = logging.getLogger(__name__)

# Default ignore patterns (in addition to .gitignore)
DEFAULT_IGNORE_PATTERNS = [
    ".code-review-graph/**",
    "node_modules/**",
    ".git/**",
    "__pycache__/**",
    "*.pyc",
    ".venv/**",
    "venv/**",
    "dist/**",
    "build/**",
    ".next/**",
    "target/**",
    "*.min.js",
    "*.min.css",
    "*.map",
    "*.lock",
    "package-lock.json",
    "yarn.lock",
    "*.db",
    "*.sqlite",
    "*.db-journal",
    "*.db-wal",
]


def find_repo_root(start: Path | None = None) -> Optional[Path]:
    """Walk up from start to find the nearest .git directory."""
    current = start or Path.cwd()
    while current != current.parent:
        if (current / ".git").exists():
            return current
        current = current.parent
    if (current / ".git").exists():
        return current
    return None


def find_project_root(start: Path | None = None) -> Path:
    """Find the project root: git repo root if available, otherwise cwd."""
    root = find_repo_root(start)
    if root:
        return root
    return start or Path.cwd()


def get_db_path(repo_root: Path) -> Path:
    """Determine the database path for a repository.

    Creates the ``.code-review-graph/`` directory and an inner ``.gitignore``
    (with ``*``) so generated files are never committed.  If a legacy
    ``.code-review-graph.db`` exists at the repo root the database is migrated
    into the new directory (WAL/SHM side-files are discarded).
    """
    crg_dir = repo_root / ".code-review-graph"
    new_db = crg_dir / "graph.db"

    # Ensure directory exists
    crg_dir.mkdir(exist_ok=True)

    # Auto-create .gitignore inside the directory (idempotent)
    inner_gitignore = crg_dir / ".gitignore"
    if not inner_gitignore.exists():
        inner_gitignore.write_text(
            "# Auto-generated by code-review-graph — do not commit database files.\n"
            "# The graph.db contains absolute paths and code structure metadata.\n"
            "*\n"
        )

    # Migrate legacy database if present
    legacy_db = repo_root / ".code-review-graph.db"
    if legacy_db.exists() and not new_db.exists():
        legacy_db.rename(new_db)
    # Discard stale WAL/SHM side-files from the old location
    for suffix in ("-wal", "-shm", "-journal"):
        side = repo_root / f".code-review-graph.db{suffix}"
        if side.exists():
            side.unlink()

    return new_db


def _load_ignore_patterns(repo_root: Path) -> list[str]:
    """Load ignore patterns from .code-review-graphignore file."""
    patterns = list(DEFAULT_IGNORE_PATTERNS)
    ignore_file = repo_root / ".code-review-graphignore"
    if ignore_file.exists():
        for line in ignore_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                patterns.append(line)
    return patterns


def _should_ignore(path: str, patterns: list[str]) -> bool:
    """Check if a path matches any ignore pattern."""
    return any(fnmatch.fnmatch(path, p) for p in patterns)


def _is_binary(path: Path) -> bool:
    """Quick heuristic: check if file appears to be binary."""
    try:
        chunk = path.read_bytes()[:8192]
        return b"\x00" in chunk
    except (OSError, PermissionError):
        return True


_GIT_TIMEOUT = 30  # seconds


def get_changed_files(repo_root: Path, base: str = "HEAD~1") -> list[str]:
    """Get list of changed files via git diff."""
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", base],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=_GIT_TIMEOUT,
        )
        if result.returncode != 0:
            # Fallback: try diff against empty tree (initial commit)
            result = subprocess.run(
                ["git", "diff", "--name-only", "--cached"],
                capture_output=True,
                text=True,
                cwd=str(repo_root),
                timeout=_GIT_TIMEOUT,
            )
        files = [f.strip() for f in result.stdout.splitlines() if f.strip()]
        return files
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def get_staged_and_unstaged(repo_root: Path) -> list[str]:
    """Get all modified files (staged + unstaged + untracked)."""
    try:
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=_GIT_TIMEOUT,
        )
        files = []
        for line in result.stdout.splitlines():
            if len(line) > 3:
                entry = line[3:].strip()
                # Handle renamed files: "R  old -> new"
                if " -> " in entry:
                    old_file, new_file = entry.split(" -> ", 1)
                    files.extend([old_file.strip(), new_file.strip()])
                    continue
                files.append(entry)
        return files
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def get_all_tracked_files(repo_root: Path) -> list[str]:
    """Get all files tracked by git."""
    try:
        result = subprocess.run(
            ["git", "ls-files"],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=_GIT_TIMEOUT,
        )
        return [f.strip() for f in result.stdout.splitlines() if f.strip()]
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def collect_all_files(repo_root: Path) -> list[str]:
    """Collect all parseable files in the repo, respecting ignore patterns."""
    ignore_patterns = _load_ignore_patterns(repo_root)
    parser = CodeParser()
    files = []

    # Prefer git ls-files for tracked files
    tracked = get_all_tracked_files(repo_root)
    if tracked:
        candidates = tracked
    else:
        # Fallback: walk directory
        candidates = [
            str(p.relative_to(repo_root))
            for p in repo_root.rglob("*")
            if p.is_file()
        ]

    for rel_path in candidates:
        if _should_ignore(rel_path, ignore_patterns):
            continue
        full_path = repo_root / rel_path
        if not full_path.is_file():
            continue
        if full_path.is_symlink():
            continue
        if parser.detect_language(full_path) is None:
            continue
        if _is_binary(full_path):
            continue
        files.append(rel_path)

    return files


def find_dependents(store: GraphStore, file_path: str) -> list[str]:
    """Find files that import from or depend on the given file.

    Looks at IMPORTS_FROM edges where target matches the file path.
    """
    dependents = set()
    # Find edges where someone imports from this file
    edges = store.get_edges_by_target(file_path)
    for e in edges:
        if e.kind == "IMPORTS_FROM":
            # The source is a file path (for IMPORTS_FROM edges)
            dependents.add(e.file_path)

    # Also check for DEPENDS_ON edges
    nodes = store.get_nodes_by_file(file_path)
    for node in nodes:
        for e in store.get_edges_by_target(node.qualified_name):
            if e.kind in ("CALLS", "IMPORTS_FROM", "INHERITS", "IMPLEMENTS"):
                dependents.add(e.file_path)

    dependents.discard(file_path)
    return list(dependents)


def _module_name_from_import(node: ast.ImportFrom) -> str:
    prefix = "." * node.level
    return f"{prefix}{node.module}" if node.module else prefix


def _iter_test_functions(tree: ast.AST):
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("test"):
            yield None, node
        elif isinstance(node, ast.ClassDef):
            for child in node.body:
                if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)) and child.name.startswith("test"):
                    yield node.name, child


def _build_test_bindings(
    parser: CodeParser,
    file_path: Path,
    tree: ast.AST,
) -> tuple[dict[str, str], dict[str, str]]:
    symbol_bindings: dict[str, str] = {}
    module_bindings: dict[str, str] = {}

    for node in tree.body:
        if isinstance(node, ast.ImportFrom):
            module_name = _module_name_from_import(node)
            for alias in node.names:
                if alias.name == "*":
                    continue
                local_name = alias.asname or alias.name.split(".")[-1]
                candidate_module = parser._join_module_path(module_name, alias.name)
                resolved_candidate = parser._resolve_module_to_file(
                    candidate_module, str(file_path), "python",
                )
                if resolved_candidate:
                    module_bindings[local_name] = candidate_module
                    continue

                resolved_symbol = parser._resolve_exported_symbol(
                    module_name, alias.name, str(file_path), "python",
                )
                if resolved_symbol:
                    symbol_bindings[local_name] = resolved_symbol

        elif isinstance(node, ast.Import):
            for alias in node.names:
                module_name = alias.name
                local_name = alias.asname or module_name.split(".", 1)[0]
                resolved_module = parser._resolve_module_to_file(
                    module_name, str(file_path), "python",
                )
                if resolved_module:
                    module_bindings[local_name] = module_name

    return symbol_bindings, module_bindings


def _refresh_tested_by_edges(
    repo_root: Path,
    store: GraphStore,
    parser: CodeParser,
    candidate_files: Optional[set[str]] = None,
) -> int:
    """Rebuild TESTED_BY edges for Python test files."""
    if candidate_files is None:
        candidate_paths = {path for path in store.get_all_files()}
    else:
        candidate_paths = {str(Path(path).resolve()) for path in candidate_files}

    test_files = [
        Path(path) for path in candidate_paths
        if path.endswith(".py")
        and "test" in Path(path).name
        and ("tests" in Path(path).parts or Path(path).name.startswith("test_"))
    ]
    if not test_files:
        return 0

    total_edges = 0
    for test_file in test_files:
        try:
            tree = ast.parse(test_file.read_text())
        except (OSError, UnicodeDecodeError, SyntaxError):
            fallback_edges = []
            for node in store.get_nodes_by_file(str(test_file)):
                if not node.is_test:
                    continue
                for edge in store.get_edges_by_source(node.qualified_name):
                    if edge.kind == "CALLS":
                        fallback_edges.append(
                            EdgeInfo(
                                kind="TESTED_BY",
                                source=node.qualified_name,
                                target=edge.target_qualified,
                                file_path=str(test_file),
                                line=0,
                            )
                        )
            store.replace_edges_for_file_kind(str(test_file), "TESTED_BY", fallback_edges)
            total_edges += len(fallback_edges)
            continue

        symbol_bindings, module_bindings = _build_test_bindings(parser, test_file, tree)
        edge_targets: set[tuple[str, str]] = set()

        for parent_class, test_func in _iter_test_functions(tree):
            targets: set[str] = set()
            for candidate in ast.walk(test_func):
                if isinstance(candidate, ast.Name):
                    target_qn = symbol_bindings.get(candidate.id)
                    if target_qn:
                        targets.add(target_qn)
                elif isinstance(candidate, ast.Attribute) and isinstance(candidate.value, ast.Name):
                    module_name = module_bindings.get(candidate.value.id)
                    if not module_name:
                        continue
                    target_qn = parser._resolve_exported_symbol(
                        module_name, candidate.attr, str(test_file), "python",
                    )
                    if target_qn:
                        targets.add(target_qn)

            source = (
                f"{test_file}::{parent_class}.{test_func.name}"
                if parent_class else f"{test_file}::{test_func.name}"
            )
            for target in targets:
                edge_targets.add((source, target))

        edges = [
            EdgeInfo(
                kind="TESTED_BY",
                source=source,
                target=target,
                file_path=str(test_file),
                line=0,
            )
            for source, target in sorted(edge_targets)
        ]
        store.replace_edges_for_file_kind(str(test_file), "TESTED_BY", edges)
        total_edges += len(edges)

    return total_edges


def full_build(repo_root: Path, store: GraphStore) -> dict:
    """Full rebuild of the entire graph."""
    parser = CodeParser()
    parser.clear_caches()
    files = collect_all_files(repo_root)

    # Purge stale data from files no longer on disk
    existing_files = set(store.get_all_files())
    current_abs = {str(repo_root / f) for f in files}
    for stale in existing_files - current_abs:
        store.remove_file_data(stale)

    total_nodes = 0
    total_edges = 0
    errors = []
    file_count = len(files)

    for i, rel_path in enumerate(files, 1):
        full_path = repo_root / rel_path
        try:
            source = full_path.read_bytes()
            fhash = hashlib.sha256(source).hexdigest()
            nodes, edges = parser.parse_bytes(full_path, source)
            store.store_file_nodes_edges(str(full_path), nodes, edges, fhash)
            total_nodes += len(nodes)
            total_edges += len(edges)
        except (OSError, PermissionError) as e:
            errors.append({"file": rel_path, "error": str(e)})
        except Exception as e:
            logger.warning("Error parsing %s: %s", rel_path, e)
            errors.append({"file": rel_path, "error": str(e)})
        if i % 50 == 0 or i == file_count:
            logger.info("Progress: %d/%d files parsed", i, file_count)

    total_edges += _refresh_tested_by_edges(repo_root, store, parser)

    store.set_metadata("last_updated", time.strftime("%Y-%m-%dT%H:%M:%S"))
    store.set_metadata("last_build_type", "full")
    store.commit()

    return {
        "files_parsed": len(files),
        "total_nodes": total_nodes,
        "total_edges": total_edges,
        "errors": errors,
    }


def incremental_update(
    repo_root: Path,
    store: GraphStore,
    base: str = "HEAD~1",
    changed_files: list[str] | None = None,
) -> dict:
    """Incremental update: re-parse changed + dependent files only."""
    parser = CodeParser()
    parser.clear_caches()
    ignore_patterns = _load_ignore_patterns(repo_root)

    # Determine changed files
    if changed_files is None:
        changed_files = get_changed_files(repo_root, base)

    if not changed_files:
        return {
            "files_updated": 0,
            "total_nodes": 0,
            "total_edges": 0,
            "changed_files": [],
            "dependent_files": [],
        }

    # Find dependent files (files that import from changed files)
    dependent_files: set[str] = set()
    for rel_path in changed_files:
        full_path = str(repo_root / rel_path)
        deps = find_dependents(store, full_path)
        for d in deps:
            # Convert back to relative path if needed
            try:
                dependent_files.add(str(Path(d).relative_to(repo_root)))
            except ValueError:
                dependent_files.add(d)

    # Combine changed + dependent
    all_files = set(changed_files) | dependent_files

    total_nodes = 0
    total_edges = 0
    errors = []

    for rel_path in all_files:
        if _should_ignore(rel_path, ignore_patterns):
            continue
        abs_path = repo_root / rel_path
        if not abs_path.is_file():
            # File was deleted
            store.remove_file_data(str(abs_path))
            continue
        if parser.detect_language(abs_path) is None:
            continue

        try:
            source = abs_path.read_bytes()
            fhash = hashlib.sha256(source).hexdigest()
            # Check if file actually changed (compare against stored file_hash column)
            existing_nodes = store.get_nodes_by_file(str(abs_path))
            if existing_nodes and existing_nodes[0].file_hash == fhash:
                # Skip unchanged files (hash match)
                continue

            nodes, edges = parser.parse_bytes(abs_path, source)
            store.store_file_nodes_edges(str(abs_path), nodes, edges, fhash)
            total_nodes += len(nodes)
            total_edges += len(edges)
        except (OSError, PermissionError) as e:
            errors.append({"file": rel_path, "error": str(e)})
        except Exception as e:
            logger.warning("Error parsing %s: %s", rel_path, e)
            errors.append({"file": rel_path, "error": str(e)})

    refresh_candidates = {str((repo_root / rel_path).resolve()) for rel_path in all_files}
    total_edges += _refresh_tested_by_edges(
        repo_root, store, parser, candidate_files=refresh_candidates,
    )

    store.set_metadata("last_updated", time.strftime("%Y-%m-%dT%H:%M:%S"))
    store.set_metadata("last_build_type", "incremental")
    store.commit()

    return {
        "files_updated": len(all_files),
        "total_nodes": total_nodes,
        "total_edges": total_edges,
        "changed_files": list(changed_files),
        "dependent_files": list(dependent_files),
        "errors": errors,
    }


# ---------------------------------------------------------------------------
# Watch mode
# ---------------------------------------------------------------------------


_DEBOUNCE_SECONDS = 0.3
_RECONCILE_SECONDS = 1.0


class _GraphWatchCoordinator:
    """Debounce and apply filesystem events for watch mode."""

    def __init__(
        self,
        repo_root: Path,
        store: GraphStore,
        parser: CodeParser,
        ignore_patterns: list[str],
        debounce_seconds: float = _DEBOUNCE_SECONDS,
    ) -> None:
        import threading

        self.repo_root = repo_root
        self.store = store
        self.parser = parser
        self.ignore_patterns = ignore_patterns
        self.debounce_seconds = debounce_seconds
        self._pending_updates: set[str] = set()
        self._pending_removals: set[str] = set()
        self._file_mtimes: dict[str, int] = {}
        self._lock = threading.Lock()
        self._execute_lock = threading.Lock()
        self._timer: threading.Timer | None = None
        self._prime_file_mtimes()

    def handle_modified(self, abs_path: str) -> None:
        if self._should_track_path(abs_path):
            self._schedule_update(abs_path)

    def handle_created(self, abs_path: str) -> None:
        if self._should_track_path(abs_path):
            self._schedule_update(abs_path)

    def handle_deleted(self, abs_path: str) -> None:
        if self._should_track_path(abs_path):
            self._schedule_removal(abs_path)

    def handle_moved(self, src_path: str, dest_path: str) -> None:
        if self._should_track_path(src_path):
            self._schedule_removal(src_path)
        if self._should_track_path(dest_path):
            self._schedule_update(dest_path)

    def handle_directory_deleted(self, abs_path: str) -> None:
        for tracked_path in self._tracked_files_in_directory(abs_path):
            self._schedule_removal(tracked_path)

    def handle_directory_created(self, abs_path: str) -> None:
        for tracked_path in self._scan_directory_files(abs_path):
            self._schedule_update(tracked_path)

    def handle_directory_moved(self, src_path: str, dest_path: str) -> None:
        self.handle_directory_deleted(src_path)
        self.handle_directory_created(dest_path)

    def _should_track_path(self, path: str) -> bool:
        candidate = Path(path)
        if candidate.is_symlink():
            return False
        try:
            rel = str(candidate.relative_to(self.repo_root))
        except ValueError:
            return False
        if _should_ignore(rel, self.ignore_patterns):
            return False
        if self.parser.detect_language(candidate) is None:
            return False
        return True

    def _prime_file_mtimes(self) -> None:
        for file_path in self.store.get_all_files():
            path = Path(file_path)
            try:
                self._file_mtimes[str(path.resolve())] = path.stat().st_mtime_ns
            except OSError:
                continue

    def _tracked_files_in_directory(self, abs_path: str) -> list[str]:
        directory = str(Path(abs_path).resolve())
        prefix = f"{directory}{Path('/')}"
        return [
            file_path for file_path in self.store.get_all_files()
            if file_path == directory or file_path.startswith(prefix)
        ]

    def _scan_directory_files(self, abs_path: str) -> list[str]:
        directory = Path(abs_path)
        if not directory.exists() or not directory.is_dir():
            return []

        tracked: list[str] = []
        for path in directory.rglob("*"):
            if not path.is_file():
                continue
            if self._should_track_path(str(path)):
                tracked.append(str(path.resolve()))
        return tracked

    def _schedule_update(self, abs_path: str) -> None:
        with self._lock:
            normalized = str(Path(abs_path).resolve())
            self._pending_updates.add(normalized)
            self._pending_removals.discard(normalized)
            self._start_timer_locked()

    def _schedule_removal(self, abs_path: str) -> None:
        with self._lock:
            normalized = str(Path(abs_path).resolve())
            if Path(normalized).exists():
                # Some editors emit a stale delete event for the destination path
                # right after an atomic replace. Keep the pending update alive.
                self._pending_updates.add(normalized)
                self._pending_removals.discard(normalized)
            else:
                self._pending_updates.discard(normalized)
                self._pending_removals.add(normalized)
            self._start_timer_locked()

    def _start_timer_locked(self) -> None:
        import threading

        if self._timer is not None:
            self._timer.cancel()
        self._timer = threading.Timer(self.debounce_seconds, self._flush)
        self._timer.start()

    def reconcile(self) -> None:
        tracked_files = {str(Path(path).resolve()) for path in self.store.get_all_files()}
        should_flush = False
        with self._lock:
            for abs_path in tracked_files:
                path = Path(abs_path)
                try:
                    mtime_ns = path.stat().st_mtime_ns
                except OSError:
                    self._pending_updates.discard(abs_path)
                    self._pending_removals.add(abs_path)
                    self._file_mtimes.pop(abs_path, None)
                    should_flush = True
                    continue

                previous_mtime = self._file_mtimes.get(abs_path)
                if previous_mtime is None:
                    self._file_mtimes[abs_path] = mtime_ns
                    continue
                if mtime_ns != previous_mtime:
                    self._pending_updates.add(abs_path)
                    self._pending_removals.discard(abs_path)
                    should_flush = True

        if should_flush:
            self._flush()

    def _flush(self) -> None:
        with self._lock:
            update_paths = list(self._pending_updates)
            removal_paths = list(self._pending_removals - self._pending_updates)
            self._pending_updates.clear()
            self._pending_removals.clear()
            self._timer = None

        with self._execute_lock:
            for abs_path in update_paths:
                self._update_file(abs_path)

            for abs_path in removal_paths:
                self._remove_file(abs_path)

    def _remove_file(self, abs_path: str) -> None:
        path = Path(abs_path)
        if path.exists():
            return

        self._file_mtimes.pop(abs_path, None)
        self.store.remove_file_data(abs_path)
        self.store.commit()
        rel = self._relative_display_path(path)
        logger.info("Removed: %s", rel)

    def _relative_display_path(self, path: Path) -> str:
        try:
            return str(path.relative_to(self.repo_root))
        except ValueError:
            return str(path)

    def _update_file(self, abs_path: str) -> None:
        path = Path(abs_path)
        if not path.is_file():
            self._remove_file(abs_path)
            return
        if path.is_symlink():
            return
        try:
            dependent_tests = {
                str(Path(dep).resolve()) for dep in find_dependents(self.store, abs_path)
                if dep.endswith(".py")
            }
            source = path.read_bytes()
            if b"\x00" in source[:8192]:
                return
            fhash = hashlib.sha256(source).hexdigest()
            self.parser.clear_caches()
            nodes, edges = self.parser.parse_bytes(path, source)
            self.store.store_file_nodes_edges(abs_path, nodes, edges, fhash)
            self._file_mtimes[abs_path] = path.stat().st_mtime_ns
            refresh_candidates = dependent_tests | {str(path.resolve())}
            _refresh_tested_by_edges(
                self.repo_root, self.store, self.parser, candidate_files=refresh_candidates,
            )
            self.store.set_metadata(
                "last_updated", time.strftime("%Y-%m-%dT%H:%M:%S")
            )
            self.store.commit()
            rel = self._relative_display_path(path)
            logger.info(
                "Updated: %s (%d nodes, %d edges)",
                rel, len(nodes), len(edges),
            )
        except OSError:
            self._remove_file(abs_path)
        except Exception as e:
            logger.error("Error updating %s: %s", abs_path, e)


def watch(repo_root: Path, store: GraphStore) -> None:
    """Watch for file changes and auto-update the graph.

    Uses a 300ms debounce to batch rapid-fire saves into a single update.
    """
    from watchdog.events import FileSystemEventHandler
    from watchdog.observers import Observer

    parser = CodeParser()
    ignore_patterns = _load_ignore_patterns(repo_root)
    coordinator = _GraphWatchCoordinator(repo_root, store, parser, ignore_patterns)

    class GraphUpdateHandler(FileSystemEventHandler):
        def on_modified(self, event):
            if event.is_directory:
                return
            coordinator.handle_modified(event.src_path)

        def on_created(self, event):
            if event.is_directory:
                coordinator.handle_directory_created(event.src_path)
                return
            coordinator.handle_created(event.src_path)

        def on_deleted(self, event):
            if event.is_directory:
                coordinator.handle_directory_deleted(event.src_path)
                return
            coordinator.handle_deleted(event.src_path)

        def on_moved(self, event):
            if event.is_directory:
                coordinator.handle_directory_moved(event.src_path, event.dest_path)
                return
            coordinator.handle_moved(event.src_path, event.dest_path)

    handler = GraphUpdateHandler()
    observer = Observer()
    observer.schedule(handler, str(repo_root), recursive=True)
    observer.start()

    logger.info("Watching %s for changes... (Ctrl+C to stop)", repo_root)
    try:
        import time as _time
        last_reconcile = 0.0
        while True:
            now = _time.monotonic()
            if now - last_reconcile >= _RECONCILE_SECONDS:
                coordinator.reconcile()
                last_reconcile = now
            _time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
    logger.info("Watch stopped.")
